langchain-ai/docs

src/langgraph-platform/deploy-hybrid.mdx, src/langgraph-platform/deploy-self-hosted-full-platform.mdx
=> docs: fix code formatting on deployment docs

src/langgraph-platform/langgraph-basics/3-add-memory.mdx
I've noticed a couple customers have gotten confused when deploying LG agents to LGP, because they configure custom checkpointers and stores. But this is not supported with LGP, because these are provided out of the box. This docs change adds a Note on step 3 of getting started which explains this.
I don't think this will stop many cases of this confusion, so long term maybe we should think about a simpler way to show "getting started on LGP". This tutorial is pretty long to begin with....
=> add note about how you dont need custom checkpointer

src/langgraph-platform/use-remote-graph.mdx
when using RemoteGraph for a couple weeks, I noticed unexpected behavior that I could give either an assistant ID or a graph name as the first argument when instantiating a RemoteGraph.
Turns out this is by design, but it was not documented.
=> better document what the first argument to a RemoteGraph can be

src/langgraph-platform/control-plane.mdx
Quick updates to the LGP Control Plane API data models.
1. Updated all of the data model heads to be plural (`Deployment` --> `Deployments`).
1. Added `Integrations` data model. This data model was always there, but we never exposed it in the API spec until recently.
1. Added `Listeners` data model. This data model is new.
1. Update `Deploy to Hybrid` page with new instructions for deploying to configuring a `Listener`. Will do this in a different PR.
=> Update LGP control plane API data models

src/langgraph-platform/deploy-hybrid.mdx, src/langgraph-platform/hybrid.mdx
Closes [LGP-420](https://linear.app/langchain/issue/LGP-420/write-best-practices-guide-for-creating-and-managing-listeners)
Add a "use cases" section for listeners to help hybrid deployment users understand how to setup/configure listeners with respect to Kubernetes clusters and LangSmith workspaces.
=> Add `Listeners > Use Cases` section for LGP `Hybrid` conceptual guide page

src/langgraph-platform/langgraph-server-changelog.mdx
Automated changelog update created by the LangGraph Server Changelog Bot.
Feel free to merge anytime.
=> docs: [LangGraph Server Changelog Bot] Changelog updates for new version(s)

src/langgraph-platform/deploy-standalone-server.mdx
this does not apply anymore, because we no longer support running standalone server without a license key
@anyone feel free to just merge this when you approve
=> fix: remove if using enterprise phrasing

src/langsmith/administration-overview.mdx, src/langsmith/release-versions.mdx
- Create new release-versions.mdx page explaining N-2 version support policy
- Add support levels: Active, Critical, End of Life, and Deprecated
- Include version support policy details and recommendations
- Add self-hosted considerations section
- Update administration overview to include the new page under Additional Resources
- Link to LangSmith changelog and Helm chart releases for current version info
=> feat: Add LangSmith Release Versions page

src/labs/swe/setup/monorepo.mdx
This PR syncs documentation files from the OpenSWE repository.
**Changes:**
- Updated MDX files from `apps/docs/`
- Target directory: `src/labs/swe/`
- Updated images from `apps/docs/images/`
- Target directory: `src/images/`
- Source commit: 504be7c5637085d477015605b0d7e2463f306a25
- Synced at 2025-08-27 19:33:53 UTC
**Auto-generated by:** OpenSWE Documentation Sync Workflow
=> Sync OpenSWE Documentation Files

src/langgraph-platform/deployment-options.mdx, src/langgraph-platform/index.mdx
This PR updates the LGP landing page to provide better direction to the quickstarts and reduce the "sales" language. Here is the preview: https://langchain-5e9cc07a-preview-lgplan-1756309673-03e45ea.mintlify.app/langgraph-platform
Also, a small update to the deployment options page to remove some clutter.
=> Update LGP landing page

src/oss/langgraph-quickstart.mdx
Minor change to the example to move the import up to make 'END' available before it was used. In the functional example, I added an import from langgraph.func of entrypoint and task, which were not there previously.
=> docs: update langgraph quickstart (py). 

src/oss/langchain-messages.mdx
Some updates to the JS examples in messages:
- let's import message primitives from `langchain` directly, same for `initChatModel`
- technically there is no difference between importing from `fs` vs `node:fs`, I think using latter gives a more clear picture that the example uses a Node.js primitive
=> fix(oss): update JS examples in messages

src/oss/release-policy.mdx, src/oss/versioning.mdx
This patch:
- shows correct package names when in JS
- fixes version example
=> fix(oss): package naming in release policy docs

src/langsmith/trace-with-langchain.mdx
Fixes DOC-62
Provides more information about the custom run name behavior. @mdrxy pointed out that the current note doesn't provide context on "LLM objects" or workarounds.
https://langchain-5e9cc07a-preview-custom-1757090078-b891f4e.mintlify.app/langsmith/trace-with-langchain#customize-run-name
=> Provide more detail in the customize run name note LS

src/langgraph-platform/reference-overview.mdx, src/langgraph-platform/release-versions.mdx, src/langsmith/docker.mdx
- Add note that Docker support is limited to local development environments only
- Clarify that container services like AWS ECS, Azure Container Instances, and Google Cloud Run are not supported
- Add prominent production warning in bold/red styling using Warning component
- Updated LangSmith Docker guide (`src/langsmith/docker.mdx`) with container service limitations
- Added clear production warning to prevent misuse in production environments
=> docs: Add Docker container service limitations and production warning

.github/ISSUE_TEMPLATE/langchain-labs.yml, .github/ISSUE_TEMPLATE/langchain.yml, .github/ISSUE_TEMPLATE/langgraph-platform.yml, .github/ISSUE_TEMPLATE/langgraph.yml, .github/ISSUE_TEMPLATE/langsmith.yml, .github/ISSUE_TEMPLATE/simple.yml
This reverts commit 3dd02825a668a2089f25487e009ef0d0130e65b8.
Also looking to fix other yaml syntax.
=> fix: templates (for the last time)?

src/langsmith/self-host-custom-tls-certificates.mdx
Modify the existing TLS Self-hosted page to be called "Custom TLS Certificates". Added a new section for mounting custom CAs into a LangSmith deployment.
- GitHub issue: 
- Feature PR: https://github.com/langchain-ai/langchainplus/pull/12017
- Linear issue: INF-758
=> Docs for Custom CA for Self-hosted deployment

src/langsmith/sample-traces.mdx
Added example of how to set different sampling rates for tracing per client. 
**Type:** Update existing documentation 
- Slack thread: https://langchain.slack.com/archives/C04GMBZ9Y1Y/p1755641768396229
=> docs(ls): set sampling rate per client

src/oss/langgraph/test.mdx
Remove duplicate import of StateGraph on testing LangGraph
**Type:** Fix typo/bug/link/formatting 
- [ x] I have read the [contributing guidelines](README.md)
- [x ] I have tested my changes locally using `docs dev`
- [x ] All code examples have been tested and work correctly
=> Remove duplicate import of StateGraph

src/oss/langgraph/test.mdx
Fixed a broken internal link on the LangGraph testing instructions page.  
The link to the **Subgraphs** page was previously pointing to the "subgraphs" page, but that doesn't exist and it should instead point to "use-subgraphs".
**Type:** Fix typo/bug/link/formatting
- GitHub issue: N/A
- Feature PR: N/A
=> langgraph docs: fix broken internal link to subgraphs page

src/langgraph-platform/api-ref-control-plane.mdx
A user didn't know that a self-hosted LGP Control Plane API host needs to have the path `/api-host`.
- Slack thread: https://langchain.slack.com/archives/C073E3GM2G0/p1758231928583519?thread_ts=1748620141.436189&cid=C073E3GM2G0
N/A
=> Add link to LS self-hosted docs in LangGraph Control Plane API reference page

src/oss/langchain/messages.mdx
Currently we split the streaming loop and combination into separate code blocks.
There are a few problems with the code block for combining chunks:
1. It doesn't work (we sum an AIMessage, which results in a ChatPromptTemplate):
```python
from langchain_core.messages import AIMessage, AIMessageChunk
chunks = [AIMessageChunk("foo"), AIMessageChunk(" bar")]
final_message = sum(chunks, AIMessage(""))  # ChatPromptTemplate
```
2. More nitpicky, but I think aggregating chunks is important and also concise enough that we can display it in the first cell with just two additional lines.
Here we demonstrate aggregation in the first cell (and also remove an import).
=> fix code cell for streaming

src/snippets/js-snippet-missing.mdx
Added a snippet for js translations. No need to merge until we need to use it. 
Idea is to make sure we have an easy way to identify which code blocks need to be translated!
=> add snippet js translation missing callout

src/docs.json, src/langsmith/alerts-webhook.mdx, src/langsmith/webhooks.mdx
Preview an updated observability sidebar. This version groups some of the pages differently to make the huge list of pages under the "configuration" group more digestible. 
Instead, the groups provide more descriptive subgroups to direct users to the correct docs area quicker.
https://langchain-5e9cc07a-preview-testob-1758285277-a523468.mintlify.app/langsmith/observability
=> Test updated observability sidebar for LangSmith

src/oss/langchain/install.mdx, src/oss/langchain/overview.mdx, src/oss/langgraph/install.mdx, src/oss/langgraph/overview.mdx
Fixed uv command.
`uv add langchain@pre` seems to be an incorrect command, and the uv equivalent of `pip install --pre` appears to be `uv add --prerelease=allow`.
**Type:** [Replace with: New documentation page / Update existing documentation / Fix typo/bug/link/formatting / Remove outdated content / Other]
Update existing documentation
- Feature PR:
=> fix: wrong uv commands

src/langgraph-platform/quick-start-studio.mdx, src/langgraph-platform/set-up-custom-auth.mdx
As a JavaScript developer I may not have Python installed and prefer a snippet using NPM.
cc @dqbd  
fwiw: I don't think [these docs](https://docs.langchain.com/langgraph-platform/local-server#node-server) are helpful for JS folks to onboard, due to following reasons:
- `npx @langchain/langgraph-cli` doesn't install langgraph CLI (it just downloads the CLI and executes it)
- `langgraph new path/to/your/app --template new-langgraph-project-js` doesn't work because the JS version of LG CLI doesn't have a `new` command, it has `dev`, `dockerfile`, `build`, `up`, `sysinfo` and `help` but no `new`
=> Advertise LG dev through NPM package

src/docs.json, src/langgraph-platform/deploy-hybrid.mdx, src/langgraph-platform/deploy-self-hosted-full-platform.mdx, src/langgraph-platform/deploy-standalone-server.mdx, src/langgraph-platform/deploy-to-cloud.mdx, src/langgraph-platform/setup-app-requirements-txt.mdx, src/langgraph-platform/setup-pyproject.mdx, src/langgraph-platform/use-remote-graph.mdx
no offense taken if disagree with these
=> nits: lgp prose

src/oss/python/integrations/tools/stripe.mdx
mirror of https://github.com/langchain-ai/langchain/pull/33044
_______
**Description:**
Stripe tools integration guide incorrectly referenced the `crewai` toolkit. Updated the import to use the correct `langchain` toolkit.
Stripe docs reference: https://docs.stripe.com/agents?framework=langchain&lang=python
=> fix stripe toolkit import in the guide

src/oss/python/integrations/providers/all_providers.mdx, src/oss/python/integrations/providers/index.mdx, src/oss/python/integrations/providers/perigon.mdx, src/oss/python/integrations/retrievers/perigon.mdx
Add the documentation for the new [perigon-langchain](https://github.com/goperigon/langchain-perigon) integration. The Perigon API suite provides fast, structured access to global news and events, helping you build real-time, data-driven products. Whether you're tracking emerging risks, surfacing relevant articles, or uncovering key insights, Perigon gives you the tools to do it programmatically.
**Type:** New documentation page
- Feature PR:
You can learn more about Perigon from the …
=> Perigon integration

src/langsmith/feedback-data-format.mdx, src/langsmith/langsmith-managed-clickhouse.mdx, src/snippets/langsmith/feedback-data-fields.mdx
Fixes DOC-353
Updates the managed ClickHouse page for specific on the stored run and feedback data. Added a table to define the run fields and whether they're stored in obj storage or CH. Added the feedback field table to a snippet and included on this page and the Feedback Data Format page.
https://langchain-5e9cc07a-preview-clarif-1758897952-a148520.mintlify.app/langsmith/langsmith-managed-clickhouse
=> Update the managed-ClickHouse page for specifics on stored fields

src/langsmith/bind-evaluator-to-dataset.mdx, src/langsmith/online-evaluations.mdx
We recently added JS Code Evals on LangSmith for both `dataset` and `session`, so updating docs to reflect this latest change!
**Type:** Update Existing Documentation 
- Linear issue: [LSP-525](https://linear.app/langchain/issue/LSP-525/create-docs-pr-js-evals)
=> fix(code-evals): added docs for js code evals [LSP-525]

src/langgraph-platform/use-remote-graph.mdx
- Add prominent warning in RemoteGraph documentation about deadlock risks
- Clarify that RemoteGraph is designed for calling graphs on other deployments
- Warn against using RemoteGraph to call the same deployment
- Added a Warning callout box in the RemoteGraph documentation
- Positioned the warning early in the document for maximum visibility
- Used clear, grammatically correct language consistent with existing documentation
RemoteGraph should not be used to call itself or another graph on the same deployment as this can lead to deadlocks and resource exhaustion. This warning helps users understand the intended use case and avoid common pitfalls.
=> Add warning about RemoteGraph deadlock risk

src/langsmith/self-host-sso.mdx
Update Okta OIDC configuration section to make it clear it is through Helm/Docker
- Feature PR:
- Linear issue: part of ent-100
=> chore: clarify Okta configuration fields

src/oss/langgraph/streaming.mdx
Inline footnotes in streaming docs.
Update existing docs to fix how they look
=> chore(langgraph): Fix footnotes in streaming docs

src/langgraph-platform/deploy-hybrid.mdx, src/langgraph-platform/self-hosted.mdx
The LGP docs for hybrid and full self hosted mention a need for configuring ingress. It might be nice to link to these docs from there.
=> Add links to ingress documentation from LGP docs

src/oss/langchain/messages.mdx
cell is not valid json, renders red
it is valid python, but since it's output I thought customary to not syntax highlight (lmk if I'm mistaken)
=> minor fix in messages guide

src/langsmith/administration-overview.mdx
Customers didn't know to include X-tenant-Id header. Doesn't hurt to mention it in the section where we explain what each API key is.
**Type:**
Update existing documentation
To automatically close an issue when this PR is merged, use closing keywords:
- Closes INF-868
- Linear issue: https://linear.app/langchain/issue/INF-868/add-to-docs-that-you-need-to-add-x-tenant-id-in-the-header-with
- [] All code examples have been tested and work correctly
- [] I have used **root relative** paths for internal links
=> Add X-Tenant-Id header info in the API key section

src/langsmith/kubernetes.mdx
Our documentation currently sends you down the path of running databases in-cluster, which is not what we want our customers doing. These changes maintain the existing instructions while advising the user to use external databases instead.
**Type:** Update existing documentation 
=> Restructure Kubernetes Install Instructions to Emphasize External Databases

src/langgraph-platform/agent-auth.mdx
we discussed two days ago with marketing and GTM that the agent auth feature will be a Beta as of the end of month launch week, so this PR marks it as such
i have no strong opinions on the best way to show this in our docs, or if it needs to be more extensive. feel free to suggest any other way of showing this.
=> mark agent auth feature as beta

src/langsmith/self-host-custom-tls-certificates.mdx
Switched the sections around so we emphasize the new way of doing. Added version requirement for new way.
Made CA for playground method optional, instead pointing to the main section.
To automatically close an issue when this PR is merged, use closing keywords:
- Closes INF-837
=> Reorganize TLS Docs for Self-Hosted

src/langsmith/self-host-sso.mdx, src/langsmith/user-management.mdx
* fix broken links
* remove incorrect SCIM setup steps (these were for without using OIN, but Okta requires using OIN)
* add missing supported features for Okta SCIM
- Feature PR:
- Linear issue: part of ent-100
=> fix: SCIM links & remove incorrect docs

build/oss/javascript/integrations/document_loaders/file_loaders/json.mdx
- Expand the no JSON pointer example for clarity.
- Correct the output of JSON pointer example.
- Minor copy changes for correctness.
**Type:** Fix typo/bug/link/formatting
=> Improve clarity in JSON loader documentation

src/snippets/trace-with-anthropic.mdx
Noticed during testing that this guide was broken + variable names were openai specific
=> fix wrap anthropic 

build/oss/python/langchain/quickstart.mdx
Fixed broken/incorrect links in the Quickstart guide to ensure readers are directed to the correct resources.
**Type:**  Fix typo/bug/link/formatting
=> fix: correct links in quickstart guide of LangChain

pipeline/preprocessors/link_map.py, src/oss/langchain/quickstart.mdx
**Type:** [Replace with: New documentation page / Update existing documentation / Fix typo/bug/link/formatting / Remove outdated content / Other]
- Feature PR:
=> fix broken links in quickstart

src/langsmith/user-management.mdx
* reference `LangSmithURL` configuration for Okta, as this is required for SCIM
* fix location of Okta supported features
- Feature PR:
- Linear issue: part of ent-100
=> fix: Okta docs instructions
