langchain-ai/docs

- src/langgraph-platform/langgraph-server-changelog.mdx
Automated changelog update created by the LangGraph Server Changelog Bot.
Feel free to merge anytime.
> docs: [LangGraph Server Changelog Bot] Changelog updates for new version(s)

- .github/workflows/create-preview-branch.yml
- src/oss/overview.mdx
https://linear.app/langchain/issue/DOC-54/automate-preview-build-in-docs
> Test auto preview branch creation

- src/oss/context.mdx
- src/oss/reference/overview.mdx
- src/oss/subgraphs.mdx
- src/oss/tools.mdx
- Fix Reference tabs for JS
- Fence in Python-specific images
- Update incorrect context code snippet
> fixes based on feedback

- src/langgraph-platform/langgraph-server.mdx
- src/langgraph-platform/plans.mdx
- src/langsmith/administration-overview.mdx
- src/langsmith/architectural-overview.mdx
- src/langsmith/cloud-architecture-and-scalability.mdx
- src/langsmith/docker.mdx
- src/langsmith/kubernetes.mdx
- src/langsmith/pricing-faq.mdx
- src/langsmith/set-up-access-control.mdx
https://linear.app/langchain/issue/DOC-70/remove-sales-references-and-direct-to-contact-sales-form
> Update sales links

- src/oss/use-graph-api.mdx
Add a tip with a link to the configurable documentation.
> Add information for setting max concurrency for parallel nodes

- src/labs/oap/quickstart.mdx
This PR syncs documentation files from the Open Agent Platform repository.
**Changes:**
- Updated MDX files from `apps/docs/`
- Target directory: `src/labs/oap/`
- Source commit: f928f231e1449f38fb8965c75c32d03a145dd6a8
- Synced at 2025-08-27 17:51:01 UTC
**Auto-generated by:** Open Agent Platform Documentation Sync Workflow
> Sync Open Agent Platform Documentation Files

- src/langsmith/script-running-pg-support-queries.mdx
part of inf-756
since we don't store the customer info in the database, add commands to query from the API and interpolate into the Postgres script
> chore: add customer info to usage event exports

- src/style.css
Found a conflict in `src/style.css` not sure which variant is the desired one, please double check.
> fix(css): resolve conflict in style.css

- src/langsmith/user-management.mdx
https://langchain-5e9cc07a-preview-linksu-1756410842-91d7376.mintlify.app/langsmith/user-management#set-up-saml-sso-for-your-organization
> Add fixes for links to User management page in LangSmith docs

- src/langgraph-platform/egress-metrics-metadata.mdx
- src/langsmith/cloud-architecture-and-scalability.mdx
- src/langsmith/self-host-egress.mdx
Customer asked about this. Let's add it to the docs.
See: https://langchain.slack.com/archives/C04GMBZ9Y1Y/p1756487091843639
> docs: add static ips for langsmith endpoints for whitelisting

- src/oss/langchain-agents.mdx
> js(agents): translate agents examples to JS

- src/oss/langchain-quickstart.mdx
Adding JS compliant example for quick start guide.
> docs(oss): add JS example to quickstart page

- src/oss/langchain-short-term-memory.mdx
Adding missing JS examples for short term memory.
> docs(oss): add JS examples for short term memory

- src/oss/langchain-long-term-memory.mdx
- src/oss/langchain-structured-output.mdx
Minor improvements on ported docs for long term memory.
> fix(oss): refine JS examples for long term memory

- src/oss/langchain-messages.mdx
- src/oss/langchain-models.mdx
Following https://github.com/langchain-ai/docs/commit/6ca0fd1682c52d89371cb5b88f0ab829afd34e0c
> Auto-format some files

- src/docs.json
- src/oss/langchain-overview.mdx
Let's remove the v1 1 pager until we have content for it.
> fix(oss): remove v1 1 pager for now

- src/oss/javascript/integrations/callbacks/index.mdx
- src/oss/javascript/integrations/chat/index.mdx
- src/oss/javascript/integrations/document_loaders/file_loaders/index.mdx
- src/oss/javascript/integrations/document_loaders/web_loaders/index.mdx
- src/oss/javascript/integrations/document_transformers/index.mdx
- src/oss/javascript/integrations/llm_caching/index.mdx
- src/oss/javascript/integrations/llms/index.mdx
- src/oss/javascript/integrations/memory/index.mdx
- src/oss/javascript/integrations/retrievers/index.mdx
- src/oss/javascript/integrations/stores/index.mdx
- src/oss/javascript/integrations/text_embedding/index.mdx
- src/oss/javascript/integrations/tools/index.mdx
- src/oss/javascript/integrations/vectorstores/index.mdx
- https://langchain.slack.com/archives/C08SC5ELSKD/p1756832212775349
> Fix card links for JS integrations

- src/oss/langchain-messages.mdx
- src/oss/langchain-models.mdx
1. hallucinated content in content block reference
2. duplicate auto-streaming content
> fix some errors

- src/oss/python/integrations/chat/openai.md
Following https://github.com/langchain-ai/langchain/releases/tag/langchain-openai%3D%3D1.0.0a2
> update ChatOpenAI page following release

- src/docs.json
- https://linear.app/langchain/issue/DOC-89/bug-when-closing-the-banner-in-documentation
> Remove banner for now

- src/oss/javascript/releases-v1.mdx
Adding JS docs counter part for its v1 alpha releases.
> feat(oss): add JS release docs

- src/labs/swe/faq.mdx
- src/labs/swe/index.mdx
- src/labs/swe/secrets.mdx
- src/labs/swe/setup/authentication.mdx
- src/labs/swe/setup/ci.mdx
- src/labs/swe/setup/development.mdx
- src/labs/swe/setup/intro.mdx
- src/labs/swe/setup/monorepo.mdx
- src/labs/swe/usage/best-practices.mdx
- src/labs/swe/usage/custom-rules.mdx
- src/labs/swe/usage/examples.mdx
- src/labs/swe/usage/github.mdx
- src/labs/swe/usage/intro.mdx
- src/labs/swe/usage/pr-tagging.mdx
- src/labs/swe/usage/ui.mdx
This PR syncs documentation files from the OpenSWE repository.
**Changes:**
- Updated MDX files from `apps/docs/`
- Target directory: `src/labs/swe/`
- Updated images from `apps/docs/images/`
- Target directory: `src/images/`
- Source commit: ef5415ddc59208389cfb941e2eaf51e03c6719e1
- Synced at 2025-09-03 22:46:53 UTC
**Auto-generated by:** OpenSWE Documentation Sync Workflow
> Sync OpenSWE Documentation Files

- .github/pull_request_template.md
decided to go with one template instead of internal vs external contributor
> add template for PRs

- .github/ISSUE_TEMPLATE/simple.yml
trying to debug why templates aren't showing up -- will remove immediately, just confirming that we can add templates w/ one that has minimalistic yaml syntax
> fix: adding test template

- src/oss/langchain/multi-agent.mdx
Adding first version of multi agent document that describes tools and handoffs.
After this PR, we still need to:
1. Update the inputs (passing the full history needs to be fixed, we should probably adjust to just incorporating another key from the state)
2. Need to fill in the sections about handoffs
> multi agent

- src/style.css
- Make tables horizontally scroll when they become longer than the content container
**Type:** Fix bug
- Slack thread: https://langchain.slack.com/archives/C04GWPE38LV/p1758118618969929
> fix table css

- src/oss/langchain/context-engineering.mdx
Fix typos in context-engineering.mdx under OSS LangChain
**Type:** Fix typo
- GitHub issue: N/A
- Feature PR: N/A
- Linear issue: N/A
- Slack thread: N/A
> docs: fix typos in context-engineering

- src/langsmith/export-traces.mdx
- src/langsmith/run-data-format.mdx
Clarify that the session_id in the API is what most users know as the tracing project ID.
**Type:**  Other
> Clarify that session_id is project ID

- .github/copilot-instructions.md
Update Copilot to ignore code snippets because it's too noisy atm
**Type:** Other
- Slack thread:  ignore the code blocks and only review prose/language
> Revise guidelines for handling MDX files and code blocks

- src/oss/langchain/middleware.mdx
Minor improvements on JS translations in middleware docs.
> fix(middleware): improve JS translations

- src/docs.json
https://www.mintlify.com/docs/navigation#enable-auto-navigation-for-groups
> feat: enable drilldown interaction

- src/langsmith/kubernetes.mdx
- src/langsmith/self-host-blob-storage.mdx
Restrict role and emphasize blob setup.
> docs: add some emphasis for setting up blob and restrict role

- AGENTS.md
since claude doesn't support it :/
> chore: add `AGENTS.md`

- src/style.css
**Type:** [Replace with: New documentation page / Update existing documentation / Fix typo/bug/link/formatting / Remove outdated content / Other]
- Feature PR:
> fix single line code block scroll

- pipeline/preprocessors/link_map.py
- src/oss/langchain/runtime.mdx
Add highlights
Add some cross-links
Fix broken tool example (tools require doc-strings in python)
Update existing documentation page.
> chore(runtime): quick fixes in the Runtime file

- reference/python/docs/langchain/agents.md
Fix title of agents page in the reference.
> chroe(reference): fix title of agents page in the reference

- src/oss/python/integrations/vectorstores/index.mdx
Updating vectorstore docs to confirm multi-tenant and standard tests support on the MongoDBAtlasVectorSearch class
- Feature PR:
> Update supported features of MongoDBAtlasVectorSearch

- reference/python/docs/langchain/rate_limiters.md
Add rate limiters to the API reference in python (no equivalent in js)
> Add rate limiters to api references

- src/docs.json
- src/oss/contributing/overview.mdx
- src/oss/javascript/integrations/providers/all_providers.mdx
- src/oss/javascript/integrations/providers/overview.mdx
- src/oss/python/integrations/providers/all_providers.mdx
- src/oss/python/integrations/providers/overview.mdx
All now have an `overview` landing page
> oss: more nav updates

- src/langsmith/self-host-sso.mdx
https://linear.app/langchain/issue/ENT-145/add-us-tld-to-default-entra-id-overrides
Adds the .us TLD for Azure Entry overrides, as well as the china and global endpoints
- GitHub issue: N/A
- Feature PR: https://github.com/langchain-ai/langchainplus/pull/12762
- Linear issue: [ENT-145/add-us-tld-to-default-entra-id-overrides](https://linear.app/langchain/issue/ENT-145/add-us-tld-to-default-entra-id-overrides)
- Slack thread: https://langchain.slack.com/archives/C08R92KKUJH/p1759433050576189
> fix: ENT-145: add us gov issuer
